### ISSUE TITLE
EDT 2022 некорректно передаются параметры запуска 1С

### ISSUE THREAD

**Issue by tormozit** [shcherbakov-vadim/edt-comparator#1]
Все настроил по инструкции. По команде "Сравнить внешней программой" процесс 1С запускается, но параметры передаются некорректно, т.к. окно сравнения табличных документов не открывается и на пол секунды появляющееся окно CMD.exe показывается ошибку "Неправильный путь ... " (дальше не успеваю разглядеть).

`"C:\Program Files (x86)\1cv8\8.3.16.1502\bin\1cv8.exe" ENTERPRISE /F"D:\DB\edt-comparator" "/CC:\Users\S1B13~1.STA\AppData\Local\Temp\1cedt\compareUsingExternalTool_Ancestor-1804685940157579131.tmp;C:\Users\S1B13~1.STA\AppData\Local\Temp\1cedt\compareUsingExternalTool_Main-17155001032428680797.tmp;C:\Users\S1B13~1.STA\AppData\Local\Temp\1cedt\compareUsingExternalTool_Other-5173587144428790725.tmp;ChartOfCharacteristicTypes.НастройкиВыполненияЗадач.Template.Предопределенные.Template (Общий родитель);ChartOfCharacteristicTypes.НастройкиВыполненияЗадач.Template.Предопределенные.Template (Рабочий каталог);ChartOfCharacteristicTypes.НастройкиВыполненияЗадач.Template.Предопределенные.Template (origin/bugfix/Release508_000371372 (004f858 [000371372]))"`

![изображение](https://user-images.githubusercontent.com/11896251/201141385-a2d756f1-dae4-48fe-bcde-6470505623d6.png)

**Comment by tormozit** [comment]
Удалось обойти эту ошибку добавлением пробела после "/C"

**Comment by tormozit** [comment]
Думаю стоит отразить это в инструкции

**Comment by shcherbakov-vadim** [comment]
> Думаю стоит отразить это в инструкции

Мне не удалось воспроизвести проблему. Я даже сделал .bat файл в котором прописал указанный вами путь и запустил на указанной вами версии платформы. 
Попробуйте тоже сделать bat файл и указать в параметрах запуска пустую ИБ, в модуле приложения которой указан следующий код:
```bsl
	Если ЗначениеЗаполнено(ПараметрЗапуска) Тогда
		Для Каждого Элемент Из СтрРазделить(ПараметрЗапуска, ";") Цикл
			Сообщить(Элемент);	
		КонецЦикла;
	КонецЕсли;
```
Пришлите полученный результат

**Comment by tormozit** [comment]
Думаю нет смысла воспроизводить ошибку, если предлагаемое исправление можно проверить и если оно у тебя корректно работает, то кажется логичным его просто принять.

Покажи свою строку запуска процесса для случая сравнения с общим предком веток гита на EDT 2022.

**Comment by shcherbakov-vadim** [comment]
> Думаю нет смысла воспроизводить ошибку, если предлагаемое исправление можно проверить и если оно у тебя корректно работает, то кажется логичным его просто принять.
> 
> Покажи свою строку запуска процесса 1С для случая сравнения с общим предком веток гита на EDT 2022.

При использовании **вашей** строки запуска все работает корректно. Я не могу просто так вносить изменения в систему без воспроизведения проблемы

**Comment by tormozit** [comment]
Перепроверил еще раз. Без пробела тоже работает. Видимо наложились еще какие то проблемы, которые были до первого достижения успеха.
