### ISSUE TITLE
Не нашел кнопки "Следующее различие" в окне сравнения табличных документов

### ISSUE THREAD

**Issue by tormozit** [shcherbakov-vadim/edt-comparator#3]
Твое окно сравнения табличных документов выглядит так. В нем нет кнопок навигации по различиям.

![изображение](https://user-images.githubusercontent.com/11896251/201277226-63d99020-fc49-4bdb-8836-d4a46fcabefe.png)

А вот окна, где они есть на платформе 8.3.22. В управляемом приложении окно открыл через подменю "Файл". В обычном приложении открыл программно.

![изображение](https://user-images.githubusercontent.com/11896251/201277558-2175980d-53c7-4cf9-b3e9-51e1fddf1396.png)

![изображение](https://user-images.githubusercontent.com/11896251/201277237-9ab8f8f0-cb01-4ed6-975a-3452c4481172.png)

**Comment by shcherbakov-vadim** [comment]
Исправлено в 38a1646f5daa7063f7501012dcc1eefd4b2dc61a
После применения изменений необходимо удалить каталоги edt,export и temp в каталоге ИБ
